### PR TITLE
Fix for #7

### PR DESCRIPTION
**Pull request by fruitcoder**
This adds support for external link references

### CODE REVIEW

**Comment by fruitcoder** [comment]
Seems to be related to an [issue](https://github.com/DoccZz/docc2html/issues/12) in the docc2html repo

**Comment by helje5** [comment]
Unfortunately that is another of those multi-issue issues :-) It carries some other thing we should implement. But yes, sounds like the link part is going to be fixed by this.

**Comment by helje5** [comment]
Ah, the other issue is already implemented. So we could close that one after a release.

**Comment by helje5** [comment]
That lacks the type alias to expose the type as part of `DocCArchive`. I suppose the whole `DocCSchema_0_1` subtype should be dropped, overengineered 🤔

**Pull request merged**
